In [37]:

#importing libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from scipy import stats

%matplotlib inline

In [38]:
#Reading the  training Dataset 
train_set = pd.read_csv('train_data.csv')

In [39]:
#Brief information regarding the training set 
train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9943 entries, 0 to 9942
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      9943 non-null   int64
 1   Aboutus                 9928 non-null   float64
 2   Aboutus_Duration        9928 non-null   float64
 3   Item_page               9928 non-null   float64
 4   Item_page_Duration      9928 non-null   float64
 5   Checkout_page           9928 non-null   float64
 6   Checkout_page_Duration  9928 non-null   float64
 7   Bounce_Rates            9928 non-null   float64
 8   Exit_Rates              9928 non-null   float64
 9   Page_Values             9943 non-null   float64
 10  Remarkable_Day          9943 non-null   float64
 11  Month                   9943 non-null   object
 12  Operating_Systems       9943 non-null   object
 13  Browser                 9943 non-null   int64
 14  Province                9943 non-null   int64
 15  TrafficType             9943 non-null   int64
 16  VisitorType             9943 non-null   object
 17  Weekend                 9943 non-null   object
 18  Income                  9943 non-null   int64
dtypes: float64(10), int64(5), object(4)
memory usage: 1.4+ MB

In [40]:
#checking  unique values
train_set.Weekend.unique()

array(['no', '1'], dtype=object)

In [41]:
#Assigning the data into a dataframe 
DataFrame1 = pd.DataFrame(train_set)

In [42]:
DataFrame1

,ID,Aboutus,Aboutus_Duration,Item_page,Item_page_Duration,Checkout_page,Checkout_page_Duration,Bounce_Rates,Exit_Rates,Page_Values,Remarkable_Day,Month,Operating_Systems,Browser,Province,TrafficType,VisitorType,Weekend,Income
0,1,0.0,0.0,1.0,10.0,9.0,700.000000,0.000000,0.011111,29.621890,0.0,Dec,Android,2,9,10,Returning_Visitor,no,1
1,2,0.0,0.0,2.0,15.0,10.0,894.666667,0.000000,0.022222,0.000000,0.0,May,Android,4,4,2,Returning_Visitor,no,0
2,3,0.0,0.0,1.0,85.0,14.0,306.500000,0.000000,0.004444,0.000000,0.0,Mar,Android,2,3,2,Returning_Visitor,no,0
3,4,0.0,0.0,5.0,175.1,26.0,615.559524,0.000000,0.002083,62.773672,0.0,Sep,Windows,1,1,3,New_Visitor,1,1
4,5,0.0,0.0,2.0,25.0,5.0,40.000000,0.066667,0.083333,0.000000,0.6,May,Android,2,1,1,Returning_Visitor,no,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9938,9939,0.0,0.0,0.0,0.0,8.0,376.333333,0.000000,0.028571,53.988000,0.0,May,Android,2,2,4,Returning_Visitor,1,1
9939,9940,1.0,46.5,1.0,0.0,22.0,671.866667,0.017391,0.020580,0.000000,0.0,Nov,iOS,2,7,10,Returning_Visitor,no,0
9940,9941,0.0,0.0,0.0,0.0,15.0,872.833333,0.000000,0.026667,0.000000,0.0,Mar,Android,2,2,3,Returning_Visitor,1,0
9941,9942,0.0,0.0,2.0,327.5,7.0,570.500000,0.000000,0.028571,0.000000,0.0,Nov,Android,2,2,2,Returning_Visitor,no,0
9942,9943,0.0,0.0,0.0,0.0,9.0,198.133333,0.000000,0.053333,0.000000,0.0,Nov,Windows,1,9,2,Returning_Visitor,no,0

In [43]:
#Dropping the ID column cause it does not affect the prediciton 
DataFrame1 = train_set.drop('ID',1)
DataFrame1

,Aboutus,Aboutus_Duration,Item_page,Item_page_Duration,Checkout_page,Checkout_page_Duration,Bounce_Rates,Exit_Rates,Page_Values,Remarkable_Day,Month,Operating_Systems,Browser,Province,TrafficType,VisitorType,Weekend,Income
0,0.0,0.0,1.0,10.0,9.0,700.000000,0.000000,0.011111,29.621890,0.0,Dec,Android,2,9,10,Returning_Visitor,no,1
1,0.0,0.0,2.0,15.0,10.0,894.666667,0.000000,0.022222,0.000000,0.0,May,Android,4,4,2,Returning_Visitor,no,0
2,0.0,0.0,1.0,85.0,14.0,306.500000,0.000000,0.004444,0.000000,0.0,Mar,Android,2,3,2,Returning_Visitor,no,0
3,0.0,0.0,5.0,175.1,26.0,615.559524,0.000000,0.002083,62.773672,0.0,Sep,Windows,1,1,3,New_Visitor,1,1
4,0.0,0.0,2.0,25.0,5.0,40.000000,0.066667,0.083333,0.000000,0.6,May,Android,2,1,1,Returning_Visitor,no,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9938,0.0,0.0,0.0,0.0,8.0,376.333333,0.000000,0.028571,53.988000,0.0,May,Android,2,2,4,Returning_Visitor,1,1
9939,1.0,46.5,1.0,0.0,22.0,671.866667,0.017391,0.020580,0.000000,0.0,Nov,iOS,2,7,10,Returning_Visitor,no,0
9940,0.0,0.0,0.0,0.0,15.0,872.833333,0.000000,0.026667,0.000000,0.0,Mar,Android,2,2,3,Returning_Visitor,1,0
9941,0.0,0.0,2.0,327.5,7.0,570.500000,0.000000,0.028571,0.000000,0.0,Nov,Android,2,2,2,Returning_Visitor,no,0
9942,0.0,0.0,0.0,0.0,9.0,198.133333,0.000000,0.053333,0.000000,0.0,Nov,Windows,1,9,2,Returning_Visitor,no,0

In [44]:
#Checking all null values in every column 
DataFrame1.isnull().sum()

Aboutus                   15
Aboutus_Duration          15
Item_page                 15
Item_page_Duration        15
Checkout_page             15
Checkout_page_Duration    15
Bounce_Rates              15
Exit_Rates                15
Page_Values                0
Remarkable_Day             0
Month                      0
Operating_Systems          0
Browser                    0
Province                   0
TrafficType                0
VisitorType                0
Weekend                    0
Income                     0
dtype: int64

In [45]:
#Filling out the null values with median value

from sklearn.impute import SimpleImputer

Column_Name = ['Aboutus','Aboutus_Duration','Item_page','Item_page_Duration','Checkout_page','Checkout_page_Duration','Bounce_Rates','Exit_Rates']

for i in Column_Name:
    DataFrame1[Column_Name] =  DataFrame1[Column_Name].fillna( DataFrame1[Column_Name].median())

In [46]:
DataFrame1.isnull().sum()

Aboutus                   0
Aboutus_Duration          0
Item_page                 0
Item_page_Duration        0
Checkout_page             0
Checkout_page_Duration    0
Bounce_Rates              0
Exit_Rates                0
Page_Values               0
Remarkable_Day            0
Month                     0
Operating_Systems         0
Browser                   0
Province                  0
TrafficType               0
VisitorType               0
Weekend                   0
Income                    0
dtype: int64

In [47]:
#finding object values in each column

for c in DataFrame1.columns:
    
    if DataFrame1[c].dtype == 'object':
        
        Unique_Valu = len(DataFrame1[c].unique())
        print(f'{c} = {Unique_Valu} number of unique values')

Month = 10 number of unique values
Operating_Systems = 8 number of unique values
VisitorType = 3 number of unique values
Weekend = 2 number of unique values

In [48]:
#Finding the number of occurences of each month  in the dataset

print(DataFrame1['Month'].value_counts().sort_values(ascending=False).head(60))

May     2711
Nov     2407
Mar     1562
Dec     1406
Oct      446
Sep      358
Jul      349
Aug      332
June     228
Feb      144
Name: Month, dtype: int64

In [49]:
#Replacing these  minimum number of occurences in Month values with 'Others'
MonthName = ['Oct','Sep','Jul','Aug','June','Feb']
for i in MonthName:
    DataFrame1['Month'] =DataFrame1['Month'].replace(i,'Others')

In [50]:
print(DataFrame1['Operating_Systems'].value_counts().sort_values(ascending=False).head(60))

Android         5357
Windows         2062
iOS             2041
Ubuntu           393
macOS             68
oracle linux      13
CentOS             5
Fedora             4
Name: Operating_Systems, dtype: int64

In [51]:
#Replacing these  minimum number of occurences in OS values with 'Others' 
OS = ['Fedora','CentOS','oracle linux','macOS']
for i in OS:
    DataFrame1['Operating_Systems'] = DataFrame1['Operating_Systems'].replace(i,'Others')

In [52]:
#Converting all categorical values into nominal values
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
EncodeColumns = ['Month','Operating_Systems','VisitorType','Weekend']
for i in EncodeColumns:
    DataFrame1[i] = LE.fit(DataFrame1[i]).transform(DataFrame1[i])

In [53]:
#Checking the correlation
DataFrame1.corr()

,Aboutus,Aboutus_Duration,Item_page,Item_page_Duration,Checkout_page,Checkout_page_Duration,Bounce_Rates,Exit_Rates,Page_Values,Remarkable_Day,Month,Operating_Systems,Browser,Province,TrafficType,VisitorType,Weekend,Income
Aboutus,1.000000,0.628791,0.370222,0.309163,0.367910,0.394566,-0.113612,-0.159494,0.047885,-0.047565,0.025755,0.011254,-0.039419,-0.033829,-0.031941,0.057024,-0.037006,0.098691
Aboutus_Duration,0.628791,1.000000,0.255338,0.227615,0.266862,0.321925,-0.073459,-0.104526,0.032931,-0.026537,0.008891,-0.013283,-0.014332,-0.026430,-0.023594,0.042157,-0.017580,0.063976
Item_page,0.370222,0.255338,1.000000,0.609614,0.427441,0.385263,-0.221621,-0.313695,0.099528,-0.097422,0.091774,-0.007195,-0.019166,-0.011960,-0.039582,-0.022276,-0.027833,0.135861
Item_page_Duration,0.309163,0.227615,0.609614,1.000000,0.283906,0.334628,-0.146486,-0.209188,0.073717,-0.074267,0.040037,0.033541,-0.007722,-0.006333,-0.015627,-0.023898,-0.016453,0.096798
Checkout_page,0.367910,0.266862,0.427441,0.283906,1.000000,0.876929,-0.203498,-0.290836,0.061747,-0.028084,0.128255,-0.115998,-0.005689,-0.043577,-0.039941,0.128318,-0.018709,0.160671
Checkout_page_Duration,0.394566,0.321925,0.385263,0.334628,0.876929,1.000000,-0.188784,-0.258474,0.058935,-0.041503,0.092104,-0.115339,-0.002096,-0.036967,-0.031999,0.123562,-0.011848,0.161664
Bounce_Rates,-0.113612,-0.073459,-0.221621,-0.146486,-0.203498,-0.188784,1.000000,0.913480,-0.120138,0.078793,-0.006611,0.131956,-0.009181,-0.001908,0.081348,0.134630,0.044743,-0.150983
Exit_Rates,-0.159494,-0.104526,-0.313695,-0.209188,-0.290836,-0.258474,0.913480,1.000000,-0.176041,0.106324,-0.025745,0.097282,0.001778,-0.005277,0.082040,0.177235,0.059345,-0.206802
Page_Values,0.047885,0.032931,0.099528,0.073717,0.061747,0.058935,-0.120138,-0.176041,1.000000,-0.060898,0.014238,-0.070921,0.049271,0.008439,0.019156,-0.108044,-0.012763,0.495673
Remarkable_Day,-0.047565,-0.026537,-0.097422,-0.074267,-0.028084,-0.041503,0.078793,0.106324,-0.060898,1.000000,-0.015663,0.002310,0.001490,-0.016178,0.056081,0.085444,0.015152,-0.078963
Month,0.025755,0.008891,0.091774,0.040037,0.128255,0.092104,-0.006611,-0.025745,0.014238,-0.015663,1.000000,0.002059,-0.040087,-0.012104,0.021417,0.016776,-0.001767,0.089864
Operating_Systems,0.011254,-0.013283,-0.007195,0.033541,-0.115998,-0.115339,0.131956,0.097282,-0.070921,0.002310,0.002059,1.000000,-0.250728,-0.033105,0.103517,0.022715,-0.122274,-0.071351
Browser,-0.039419,-0.014332,-0.019166,-0.007722,-0.005689,-0.002096,-0.009181,0.001778,0.049271,0.001490,-0.040087,-0.250728,1.000000,0.099251,0.115927,-0.017163,0.041805,0.023908
Province,-0.033829,-0.026430,-0.011960,-0.006333,-0.043577,-0.036967,-0.001908,-0.005277,0.008439,-0.016178,-0.012104,-0.033105,0.099251,1.000000,0.044360,-0.032948,0.000815,-0.012431
TrafficType,-0.031941,-0.023594,-0.039582,-0.015627,-0.039941,-0.031999,0.081348,0.082040,0.019156,0.056081,0.021417,0.103517,0.115927,0.044360,1.000000,-0.001897,0.002335,-0.011074
VisitorType,0.057024,0.042157,-0.022276,-0.023898,0.128318,0.123562,0.134630,0.177235,-0.108044,0.085444,0.016776,0.022715,-0.017163,-0.032948,-0.001897,1.000000,0.043503,-0.111349
Weekend,-0.037006,-0.017580,-0.027833,-0.016453,-0.018709,-0.011848,0.044743,0.059345,-0.012763,0.015152,-0.001767,-0.122274,0.041805,0.000815,0.002335,0.043503,1.000000,-0.027183
Income,0.098691,0.063976,0.135861,0.096798,0.160671,0.161664,-0.150983,-0.206802,0.495673,-0.078963,0.089864,-0.071351,0.023908,-0.012431,-0.011074,-0.111349,-0.027183,1.000000

In [54]:
DataFrame1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9943 entries, 0 to 9942
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Aboutus                 9943 non-null   float64
 1   Aboutus_Duration        9943 non-null   float64
 2   Item_page               9943 non-null   float64
 3   Item_page_Duration      9943 non-null   float64
 4   Checkout_page           9943 non-null   float64
 5   Checkout_page_Duration  9943 non-null   float64
 6   Bounce_Rates            9943 non-null   float64
 7   Exit_Rates              9943 non-null   float64
 8   Page_Values             9943 non-null   float64
 9   Remarkable_Day          9943 non-null   float64
 10  Month                   9943 non-null   int32
 11  Operating_Systems       9943 non-null   int32
 12  Browser                 9943 non-null   int64
 13  Province                9943 non-null   int64
 14  TrafficType             9943 non-null   int64
 15  VisitorType             9943 non-null   int32
 16  Weekend                 9943 non-null   int32
 17  Income                  9943 non-null   int64
dtypes: float64(10), int32(4), int64(4)
memory usage: 1.2 MB

In [55]:
DataFrame1

,Aboutus,Aboutus_Duration,Item_page,Item_page_Duration,Checkout_page,Checkout_page_Duration,Bounce_Rates,Exit_Rates,Page_Values,Remarkable_Day,Month,Operating_Systems,Browser,Province,TrafficType,VisitorType,Weekend,Income
0,0.0,0.0,1.0,10.0,9.0,700.000000,0.000000,0.011111,29.621890,0.0,0,0,2,9,10,2,1,1
1,0.0,0.0,2.0,15.0,10.0,894.666667,0.000000,0.022222,0.000000,0.0,2,0,4,4,2,2,1,0
2,0.0,0.0,1.0,85.0,14.0,306.500000,0.000000,0.004444,0.000000,0.0,1,0,2,3,2,2,1,0
3,0.0,0.0,5.0,175.1,26.0,615.559524,0.000000,0.002083,62.773672,0.0,4,3,1,1,3,0,0,1
4,0.0,0.0,2.0,25.0,5.0,40.000000,0.066667,0.083333,0.000000,0.6,2,0,2,1,1,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9938,0.0,0.0,0.0,0.0,8.0,376.333333,0.000000,0.028571,53.988000,0.0,2,0,2,2,4,2,0,1
9939,1.0,46.5,1.0,0.0,22.0,671.866667,0.017391,0.020580,0.000000,0.0,3,4,2,7,10,2,1,0
9940,0.0,0.0,0.0,0.0,15.0,872.833333,0.000000,0.026667,0.000000,0.0,1,0,2,2,3,2,0,0
9941,0.0,0.0,2.0,327.5,7.0,570.500000,0.000000,0.028571,0.000000,0.0,3,0,2,2,2,2,1,0
9942,0.0,0.0,0.0,0.0,9.0,198.133333,0.000000,0.053333,0.000000,0.0,3,3,1,9,2,2,1,0

In [56]:
#Converting Categorical columns into numeric columns via OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
Hot = OneHotEncoder()
HotEncoder = Hot.fit(DataFrame1[['Month','Operating_Systems','VisitorType','Weekend']]).transform(DataFrame1[['Month','Operating_Systems','VisitorType','Weekend']])

In [57]:
Temp = pd.DataFrame(HotEncoder.toarray(), columns=Hot.get_feature_names() )

In [58]:
Temp

,x0_0,x0_1,x0_2,x0_3,x0_4,x1_0,x1_1,x1_2,x1_3,x1_4,x2_0,x2_1,x2_2,x3_0,x3_1
0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9938,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
9939,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
9940,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
9941,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
9942,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0

In [59]:
DataFrame2 = pd.concat([Temp, DataFrame1[['Aboutus','Aboutus_Duration','Item_page','Item_page_Duration','Checkout_page','Checkout_page_Duration','Bounce_Rates','Exit_Rates','Page_Values','Remarkable_Day','Browser','Province','TrafficType','Income']]], axis=1, join='inner')

In [60]:
DataFrame2

,x0_0,x0_1,x0_2,x0_3,x0_4,x1_0,x1_1,x1_2,x1_3,x1_4,...,Checkout_page,Checkout_page_Duration,Bounce_Rates,Exit_Rates,Page_Values,Remarkable_Day,Browser,Province,TrafficType,Income
0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,9.0,700.000000,0.000000,0.011111,29.621890,0.0,2,9,10,1
1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,10.0,894.666667,0.000000,0.022222,0.000000,0.0,4,4,2,0
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,14.0,306.500000,0.000000,0.004444,0.000000,0.0,2,3,2,0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,26.0,615.559524,0.000000,0.002083,62.773672,0.0,1,1,3,1
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,5.0,40.000000,0.066667,0.083333,0.000000,0.6,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9938,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,8.0,376.333333,0.000000,0.028571,53.988000,0.0,2,2,4,1
9939,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,22.0,671.866667,0.017391,0.020580,0.000000,0.0,2,7,10,0
9940,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,15.0,872.833333,0.000000,0.026667,0.000000,0.0,2,2,3,0
9941,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,7.0,570.500000,0.000000,0.028571,0.000000,0.0,2,2,2,0
9942,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,9.0,198.133333,0.000000,0.053333,0.000000,0.0,1,9,2,0

In [61]:
#Choosing only the dependent variables for X
X = DataFrame2.drop('Income',1)
#Choosing only the independent variable for Y
Y = DataFrame2['Income']

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30)

In [63]:

from sklearn.ensemble import RandomForestClassifier
Classifier = RandomForestClassifier(n_estimators = 250, max_depth=16,  criterion ='gini' )
Classifier.fit(X_train, Y_train)

RandomForestClassifier(max_depth=16, n_estimators=250)

In [64]:
Y_pred = Classifier.predict(X_test)

In [65]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
Result = accuracy_score(Y_test,Y_pred)
print("Accuracy:",Result)

Accuracy: 0.9014415018437815

In [ ]:
from sklearn.svm import SVC
Model = SVC(kernel= 'linear')

In [ ]:
Model.fit(X_train,Y_train)

In [ ]:
Model_Score = Model.score(X_test,Y_test)

In [ ]:
print(Model_Score)

In [ ]:
print(Y_pred)
print(Y_test)